---
# yaml-language-server: $schema=../../bundle-schema.json
resources:
  pipelines:
    calgary_transit_ingest_pipeline:
      name: calgary_transit_ingest
      catalog: ${var.catalog_name}
      schema: ${resources.schemas.calgary_transit_schema.name}
      serverless: true
      libraries:
        - file:
            path: ../../workflows/calgary_transit_ingest_pipeline.py
      environment:
        dependencies:
          - '../../dist/*.whl'
          # Use editable install to always pick up the latest deployed code
          # instead of the wheel built at deploy time:
          # - --editable ${workspace.file_path}
